version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    network_mode: host
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - prisma
  prisma:
    container_name: prisma
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app
      - /app/node_modules
    command: >
      sh -c "npm run prisma:generate &&
             npm run migration:dev &&
             npm run seed"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boards_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports: 
      - 5050:80
    volumes:
      - /var/lib/pgadmin

volumes:
  pgdata: