export enum ActivityTypes{
    ADD_CARD = 'ADD CARD',
    REMOVE_CARD = 'REMOVE CARD',
    ADD_COMMENT_TO_CARD = 'ADD COMMENT TO CARD',
    MOVE_CARD_TO_ANOTHER_LIST = 'MOVE CARD TO ANOTHER LIST',
    REMOVE_LIST = 'REMOVE LIST'
}